export const allData = {
  companyInfo: {
    companyName: "Alexander, Bogan and Feeney",
    companyMotto: "front-end orchestrate niches",
    companyEst: "2024-08-22T12:54:40.785Z",
  },
  employees: [
    {
      id: "ff438984-f69b-48e2-8a7e-ea96ed4a8a84",
      avatar:
        "https://s3.amazonaws.com/uifaces/faces/twitter/clubb3rry/128.jpg",
      firstName: "Claudia",
      lastName: "Davis",
      jobTitle: "Lead Mobility Officer",
      contactNo: "0489 393 609",
      address: "Adam Boulevard Jakefurt, Tasmania",
      age: 25,
      bio: "Quaerat quam numquam est aut. Provident at ut. Ut fuga quia et voluptas earum incidunt veritatis praesentium tempora.",
      dateJoined: "2021-02-03T09:42:29.249Z",
    },
    {
      id: "1723c67c-f7e2-45b6-a6cb-dae99b5fc41d",
      avatar:
        "https://s3.amazonaws.com/uifaces/faces/twitter/dansowter/128.jpg",
      firstName: "Ethan",
      lastName: "Welch",
      jobTitle: "Human Identity Executive",
      contactNo: "0444 906 518",
      address: "Wilkinson Knoll Amelialand, Tasmania",
      age: 43,
      bio: "Voluptates totam reiciendis recusandae. Non numquam praesentium distinctio delectus ut veritatis assumenda. Libero ut veniam. Qui et eos eligendi culpa explicabo sit et asperiores ea.",
      dateJoined: "2022-08-30T01:50:39.008Z",
    },
    {
      id: "1b816b03-e3df-4af4-8453-1df9100168cf",
      avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/adamsxu/128.jpg",
      firstName: "Elijah",
      lastName: "Lewis",
      jobTitle: "Central Metrics Consultant",
      contactNo: "0449 327 304",
      address: "Isabella Hill Lake Victoriaport, New South Wales",
      age: 20,
      bio: "Ea suscipit recusandae dolor. Rerum laboriosam et rerum numquam eum laborum repellendus cumque ea. Unde pariatur tempore mollitia in magnam blanditiis quia voluptas occaecati. Quod mollitia reprehenderit et unde sunt enim officia rerum officiis. Earum culpa commodi. Animi repellat deserunt veniam deleniti id quis delectus impedit.",
      dateJoined: "2024-10-16T17:23:09.793Z",
    },
    {
      id: "960fa211-8c32-4434-b7cb-8165247dcde6wc2022_Qatar",
      avatar:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRiVXifW5DiGm_rVyzuQQr23htCshfltFt5JUv0OsCT167UG8ERfwyCSg&s",
      firstName: "Messi",
      lastName: "Lionel",
      jobTitle: "Footballer",
      contactNo: "0000 526 555",
      address: "Rosario Santa Fe, Argentina",
      age: 38,
      bio: "Argentine professional footballer who plays as a forward for and captains both Major League Soccer club Inter Miami and the Argentina national team. Widely regarded as one of the greatest players of all time",
      dateJoined: "2022-06-24T12:52:55.495Z",
    },
    {
      id: "960fa211-8c32-4434-b7cb-8165247dcde6-euro2016_Paris",
      avatar:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3okDOW2_XIpI26z1iFqytJNimBA7xxpJDfAjKM-g-oTaT1ybX8z14iXjCCSFKDUB1cMU&usqp=CAU",
      firstName: "Cristiano",
      lastName: "Ronaldo",
      jobTitle: "Footballer",
      contactNo: "0001 526 777",
      address: " Madeira, Portugal",
      age: 40,
      bio: "Portuguese professional footballer who plays as a forward for and captains both the Saudi Pro League club Al Nassr and the Portugal national team. Widely regarded as one of the greatest players of all time",
      dateJoined: "2022-06-24T12:52:55.495Z",
    },
    {
      id: "42d958dc-04b1-4163-8887-b55118246e63",
      avatar:
        "https://s3.amazonaws.com/uifaces/faces/twitter/panchajanyag/128.jpg",
      firstName: "Jasper",
      lastName: "Klein",
      jobTitle: "Principal Communications Director",
      contactNo: "0424 412 379",
      address: "Caleb Circle Johnsville, Northern Territory",
      age: 42,
      bio: "Odit fugiat placeat explicabo assumenda odit culpa voluptas ducimus. Atque laboriosam assumenda aliquid maxime qui vitae eos libero omnis. Omnis occaecati occaecati fugiat qui architecto consequatur aut omnis. Consequatur ab voluptas pariatur est quas laudantium voluptatem laudantium numquam. Ipsam asperiores ut libero ut.",
      dateJoined: "2023-01-17T21:35:38.401Z",
    },
    {
      id: "ece3f7b4-4b03-4743-bf6a-e7759d7996e2",
      avatar:
        "https://s3.amazonaws.com/uifaces/faces/twitter/akashsharma39/128.jpg",
      firstName: "Christian",
      lastName: "Christiansen",
      jobTitle: "Customer Group Officer",
      contactNo: "0447 281 204",
      address: "Taylor Court East Evieview, South Australia",
      age: 35,
      bio: "Temporibus repudiandae ipsum ullam perferendis error odit aut sed. Saepe esse veniam et qui maiores non non. Debitis ut eligendi accusantium unde quo cupiditate id. Dolor et quos aut. Eos consectetur voluptas at soluta amet et. Officiis perferendis est suscipit.",
      dateJoined: "2018-03-22T15:45:31.571Z",
    },
    {
      id: "c2d75f08-cec2-4d45-942b-22c1bf240134",
      avatar:
        "https://s3.amazonaws.com/uifaces/faces/twitter/Shriiiiimp/128.jpg",
      firstName: "David",
      lastName: "Schmidt",
      jobTitle: "Customer Usability Executive",
      contactNo: "0403 760 668",
      address: "Glover Square Johnstonside, Western Australia",
      age: 32,
      bio: "Corrupti a saepe voluptas sed aperiam magni et mollitia et. Vitae voluptas quia. Quia et ut ad quia rem aut ut itaque. Sunt unde harum optio necessitatibus impedit qui. Quibusdam ab occaecati similique aspernatur quia nobis veniam non enim.",
      dateJoined: "2019-11-24T16:55:24.962Z",
    },
    {
      id: "29e0fc61-dbc3-4d6e-a437-2a23e1fc8957",
      avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/magoo04/128.jpg",
      firstName: "Hugo",
      lastName: "Hyatt",
      jobTitle: "Legacy Directives Manager",
      contactNo: "0440 859 638",
      address: "Stewart Run Lake Gabriellahaven, South Australia",
      age: 34,
      bio: "Facere et inventore libero. Impedit qui aut et earum ipsum voluptates fugiat et voluptates. Itaque culpa eum est aspernatur.",
      dateJoined: "2024-07-04T23:16:44.165Z",
    },
    {
      id: "35bb2e62-fc50-451d-9edc-3480eea68e08",
      avatar:
        "https://s3.amazonaws.com/uifaces/faces/twitter/pcridesagain/128.jpg",
      firstName: "Aaron",
      lastName: "Davies",
      jobTitle: "Central Factors Consultant",
      contactNo: "0481 903 439",
      address: "Lara Square Gracefort, Victoria",
      age: 65,
      bio: "Aliquam iste et quod fugiat qui ad et fugiat. Quod iste nam rerum sint consequatur. Rerum et sit. Error velit enim. Dicta error ipsam et officiis recusandae dolores minus. Et fuga alias non itaque ipsam.",
      dateJoined: "2022-09-13T14:45:11.289Z",
    },
    {
      id: "3c86465b-a36f-47d4-b156-5193f5c8b506",
      avatar:
        "https://s3.amazonaws.com/uifaces/faces/twitter/erwanhesry/128.jpg",
      firstName: "Violet",
      lastName: "Gibson",
      jobTitle: "Customer Division Analyst",
      contactNo: "0494 193 577",
      address: "Swift Crest New Madelinestad, Queensland",
      age: 20,
      bio: "Doloremque nemo rerum. Voluptas doloremque quo dignissimos qui vel nulla assumenda eum et. Maiores est voluptatem nostrum.",
      dateJoined: "2023-10-09T23:12:20.467Z",
    },
    {
      id: "e33b8789-bc59-4ab4-a727-bff4eda20930",
      avatar:
        "https://s3.amazonaws.com/uifaces/faces/twitter/aviddayentonbay/128.jpg",
      firstName: "Taylor",
      lastName: "Haley",
      jobTitle: "Central Intranet Representative",
      contactNo: "0476 512 661",
      address: "Elizabeth Island North Alexis, Victoria",
      age: 43,
      bio: "Aut eos odit reprehenderit qui id odit iure. Eveniet sit ea. Architecto optio maiores inventore rerum est non in. In explicabo quod voluptate provident ut quia quisquam officia quod. Aut mollitia hic molestias. Nihil ut voluptatibus consequatur.",
      dateJoined: "2024-11-24T04:58:20.070Z",
    },
    {
      id: "a8a90476-e9a3-489a-a754-161cf98d35f9",
      avatar:
        "https://s3.amazonaws.com/uifaces/faces/twitter/maximseshuk/128.jpg",
      firstName: "Patrick",
      lastName: "Wilderman",
      jobTitle: "Lead Paradigm Supervisor",
      contactNo: "0405 873 482",
      address: "Hessel Square North Aidanside, South Australia",
      age: 64,
      bio: "Consectetur perferendis illo temporibus. Consequatur sit culpa incidunt tenetur laudantium quod et aut. Explicabo nisi maiores illum nam itaque vero ipsum tenetur nihil. Reprehenderit qui quaerat.",
      dateJoined: "2016-12-15T10:26:40.998Z",
    },
    {
      id: "960fa211-8c32-4434-b7cb-8165247dcde6",
      avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/jydesign/128.jpg",
      firstName: "Molly",
      lastName: "Jacobs",
      jobTitle: "Human Assurance Analyst",
      contactNo: "0441 526 451",
      address: "Mclaughlin Estate Dr Boscoville, Western Australia",
      age: 54,
      bio: "Maxime omnis hic. Numquam temporibus iusto cum illum repellat explicabo vero. Cumque dolorem ex dolores ducimus rerum.",
      dateJoined: "2022-06-24T12:52:55.495Z",
    },
  ],
};
